name: Scarb Formatting Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SCARB_VERSION: 2.8.5
  CAIRO_VERSION: 2.8.5

jobs:  
  format-check:
    name: Scarb Formatting Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Scarb
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh -s -- -v $SCARB_VERSION
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: check formatting
        run: scarb fmt --check